import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme/themeProvider";
import { SplashGate } from "@/components/shell/SplashGate";
import { DockPortal } from "@/components/shell/DockPortal";
import { Loader } from "@/components/Loader/loader";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider defaultMode="system" defaultAccent="violet">
          <SplashGate durationMs={4500} Loader={Loader}>
            {children}
            <DockPortal />
          </SplashGate>
        </ThemeProvider>
      </body>
    </html>
  );
}
